// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7oFyiL0e3nUBSDMyN9ftwETsk2bEzOCg',
    appId: '1:854446184866:web:9096221db1d5e89508bafb',
    messagingSenderId: '854446184866',
    projectId: 'piddle-final',
    authDomain: 'piddle-final.firebaseapp.com',
    storageBucket: 'piddle-final.appspot.com',
    measurementId: 'G-HJRVRBMMBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYhkkSNTPGCPDH8AHJwvmy72o_9KTWOWs',
    appId: '1:854446184866:android:d4e27957df23d43c08bafb',
    messagingSenderId: '854446184866',
    projectId: 'piddle-final',
    storageBucket: 'piddle-final.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1f6s18ZjjrObSsHmKQeE9Rsh7DwCyq6E',
    appId: '1:854446184866:ios:50aee6b5146967f408bafb',
    messagingSenderId: '854446184866',
    projectId: 'piddle-final',
    storageBucket: 'piddle-final.appspot.com',
    iosClientId: '854446184866-5irn3m9p66gl2srn29ak310en8bkpmov.apps.googleusercontent.com',
    iosBundleId: 'com.example.piddleFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1f6s18ZjjrObSsHmKQeE9Rsh7DwCyq6E',
    appId: '1:854446184866:ios:50aee6b5146967f408bafb',
    messagingSenderId: '854446184866',
    projectId: 'piddle-final',
    storageBucket: 'piddle-final.appspot.com',
    iosClientId: '854446184866-5irn3m9p66gl2srn29ak310en8bkpmov.apps.googleusercontent.com',
    iosBundleId: 'com.example.piddleFinal',
  );
}
