// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo-TMqPrYEY7w_cLPslXIJf2yE0ikOiK8',
    appId: '1:466200283784:web:cd6405ab0566ad7e186d3d',
    messagingSenderId: '466200283784',
    projectId: 'piddle-two',
    authDomain: 'piddle-two.firebaseapp.com',
    storageBucket: 'piddle-two.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdYwlveubt03hDVJfjrB8PKhD-OS8FRf4',
    appId: '1:466200283784:android:922c4a69bb61535c186d3d',
    messagingSenderId: '466200283784',
    projectId: 'piddle-two',
    storageBucket: 'piddle-two.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXP1a18TlPM_Kvw2B8eq-Ww2avfdIvPCo',
    appId: '1:466200283784:ios:0d1eb06b9c403951186d3d',
    messagingSenderId: '466200283784',
    projectId: 'piddle-two',
    storageBucket: 'piddle-two.appspot.com',
    iosClientId: '466200283784-290e9ln6u0bmqrvn0t79va1q5m4c0etn.apps.googleusercontent.com',
    iosBundleId: 'com.example.piddleTwo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXP1a18TlPM_Kvw2B8eq-Ww2avfdIvPCo',
    appId: '1:466200283784:ios:0d1eb06b9c403951186d3d',
    messagingSenderId: '466200283784',
    projectId: 'piddle-two',
    storageBucket: 'piddle-two.appspot.com',
    iosClientId: '466200283784-290e9ln6u0bmqrvn0t79va1q5m4c0etn.apps.googleusercontent.com',
    iosBundleId: 'com.example.piddleTwo',
  );
}
